version: '3.8'

services:
  # --- 1. MySQL (Para Usuarios y Auth) ---
  mysql_db:
    image: mysql:8.0
    container_name: lab_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Contraseña maestra
      MYSQL_DATABASE: lab_usuarios       # Base de datos inicial
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # --- 2. MongoDB (Para Inventario de Laboratorios) ---
  mongo_db:
    image: mongo:latest
    container_name: lab_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  # --- 3. Redis (Para Caché y Monitoreo/Heartbeat) ---
  redis_db:
    image: redis:alpine
    container_name: lab_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  mongo_data:
  redis_data: