version: '3.8'

services:
  # --- BASES DE DATOS ---
  mysql_db:
    image: mysql:8.0
    container_name: lab_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lab_usuarios
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - lab_net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "user", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 10

  mongo_db:
    image: mongo:latest
    container_name: lab_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    ports:
      - "27018:27017" # Mapeo externo 27018 -> interno 27017
    volumes:
      - mongo_data:/data/db
    networks:
      - lab_net

  redis_db:
    image: redis:alpine
    container_name: lab_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - lab_net

  # --- APLICACIONES ---
  
  # Backend 1 (Instancia Principal)
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: lab_backend_1
    restart: always
    ports:
      - "8001:8000" # Accederemos desde localhost:8001
    environment:
      PORT: 8001
      # OJO: Dentro de Docker, los hostnames son los nombres de servicio
      MYSQL_URL: "mysql+pymysql://user:password@mysql_db:3306/lab_usuarios"
      MONGO_URL: "mongodb://admin:adminpassword@mongo_db:27017"
      REDIS_URL: "redis://redis_db:6379"
    depends_on:
      mysql_db:
        condition: service_healthy # Espera a que MySQL est√© realmente listo
      mongo_db:
        condition: service_started
    networks:
      - lab_net

  # Frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lab_frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8001
      - CHOKIDAR_USEPOLLING=true # Obliga a Vite a detectar cambios en Windows
    stdin_open: true # Mantiene la terminal abierta
    tty: true
    networks:
      - lab_net

volumes:
  mysql_data:
  mongo_data:
  redis_data:

networks:
  lab_net:
    driver: bridge